# Generated by Django 5.0.13 on 2025-04-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_date_birth_remove_user_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=150, null=True, verbose_name='имя'),
        ),
    ]
