# Generated by Django 5.0.13 on 2025-04-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=150, null=True, verbose_name='фамилия'),
        ),
    ]
