# Generated by Django 5.0.13 on 2025-04-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='Anonymous', max_length=150, null=True, verbose_name='имя'),
        ),
    ]
