# Generated by Django 5.0.13 on 2025-05-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_productid_orderproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalSum',
            field=models.IntegerField(default=0, verbose_name='сумма заказа'),
        ),
    ]
