# Generated by Django 5.0.13 on 2025-03-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_parrentcategory_product_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='parrentcategory',
            options={'verbose_name': 'ParentCategory', 'verbose_name_plural': 'ParentCategories'},
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
