# Generated by Django 5.0.13 on 2025-03-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
