# Generated by Django 5.0.13 on 2025-04-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='parrentcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/parent_categories_images/', verbose_name='parent Category Image'),
        ),
    ]
