# Generated by Django 5.0.13 on 2025-04-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата Рождения'),
        ),
    ]
