# Generated by Django 5.0.13 on 2025-04-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_date_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_birth',
        ),
    ]
