# Generated by Django 5.0.13 on 2025-05-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_date_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_slider',
            field=models.BooleanField(default=False, verbose_name='slider'),
        ),
    ]
