# Generated by Django 5.0.13 on 2025-05-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_category_has_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name', 'priority'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='parrentcategory',
            options={'ordering': ['id', 'priority'], 'verbose_name': 'ParentCategory', 'verbose_name_plural': 'ParentCategories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id', 'priority'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='parrentcategory',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='category',
            name='has_slider',
            field=models.BooleanField(default=False, verbose_name='Создать слайдер с категорией'),
        ),
    ]
