# Generated by Django 5.0.13 on 2025-05-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_category_options_alter_parrentcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-priority', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='parrentcategory',
            options={'ordering': ['-priority', 'id'], 'verbose_name': 'ParentCategory', 'verbose_name_plural': 'ParentCategories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-priority', 'id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
