# Generated by Django 5.0.13 on 2025-05-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
    ]
