# Generated by Django 5.0.13 on 2025-05-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_category_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(related_name='products_lists', to='products.product', verbose_name='add product'),
        ),
    ]
