# Generated by Django 5.0.13 on 2025-05-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_category_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='products_lists', to='products.product', verbose_name='add product'),
        ),
    ]
