# Generated by Django 5.0.13 on 2025-05-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_category_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParrentCategory',
            new_name='ParentCategory',
        ),
    ]
