# Generated by Django 5.0.13 on 2025-06-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Composition',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Composition'),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='original price'),
        ),
    ]
