# Generated by Django 5.0.13 on 2025-06-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_composition_alter_product_original_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Composition',
            new_name='composition',
        ),
    ]
