# Generated by Django 5.0.13 on 2025-06-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_rename_composition_product_composition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.AddField(
            model_name='product',
            name='Composition',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Composition'),
        ),
    ]
