# Generated by Django 5.2.3 on 2025-09-28 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_category_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.category', verbose_name='Category'),
        ),
    ]
